POST http://localhost:8080/api/members/jsgrid.json HTTP/1.1
content-type: application/json

{
    "pageIndex": 1,
    "pageSize": 10,
    "sortField": "username",
    "sortOrder": "desc"
}
### 사용자 추가
POST http://localhost:8080/api/members HTTP/1.1
content-type: application/json

{
  "username": "appsoga",
  "password": "{bcrypt}$2a$10$B/oPhZRQILgGrSrlWJ1J2O3UdUa/PMWIo8vg0WtQZmrObf62fT63C",
  "email": null,
  "name": "sangmok",
  "expiresOn": null,
  "lastAccessedOn": null,
  "enabled": true
}

### 사용자 조회
GET http://localhost:8080/api/members/301 HTTP/1.1

### 사용자 수정
PUT http://localhost:8080/api/members HTTP/1.1
content-type: application/json

{
    "id":301,
    "group":10,
    "name":"admin",
    "email":"",
    "username":"admin",
    "password":"{bcrypt}$2a$10$3uLLZOWt4W/Pa0Fq50Q87.xA/o7UaVjbQsTZ6yZSTYump0i/zlf9i",
    "enabled":true,
    "expiresOn":"2020-12-31T02:18:00.612Z",
    "lastAccessedOn":"2019-11-16T02:18:00.612Z"
}

### 사용자 삭제
DELETE http://localhost:8080/api/members/1 HTTP/1.1



### datatable 테스트
GET http://localhost:8080/app/member/datatable.json HTTP/1.1

list: 66 {
    "draw": 17,
    "columns": [
        {
            "data": "id",
            "name": "id",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "username",
            "name": "username",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "name",
            "name": "name",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "1024",
                "regex": false
            }
        },
        {
            "data": "email",
            "name": "email",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "expiresOn",
            "name": "expiresOn",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        }
    ],
    "order": [
        {
            "column": 0,
            "dir": "asc"
        }
    ],
    "start": 0,
    "length": 25,
    "search": {
        "value": "1024",
        "regex": false
    }
}