GET http://localhost:8080/api/members/jsgrid HTTP/1.1
content-type: application/json

{
    "pageIndex": 0,
    "pageSize": 12,
    "sortField": "username",
    "sortOrder": "desc",

    "username": "admin",
}


### 사용자 추가
POST http://localhost:8080/api/members HTTP/1.1
content-type: application/json

{
  "username": "appsoga",
  "password": "{bcrypt}$2a$10$B/oPhZRQILgGrSrlWJ1J2O3UdUa/PMWIo8vg0WtQZmrObf62fT63C",
  "email": null,
  "name": "sangmok",
  "expiresOn": null,
  "lastAccessedOn": null,
  "enabled": true
}

### 사용자 조회
GET http://localhost:8080/api/members/1 HTTP/1.1

### 사용자 수정
PUT http://localhost:8080/api/members HTTP/1.1
content-type: application/json

{
  "id": 1,
  "name": "jhon smith",
  "email": "root@linux.com",
  "username": "user1",
  "expiresOn": null,
  "lastAccessedOn": null,
  "enabled": true
}

### 사용자 삭제
DELETE http://localhost:8080/api/members/1 HTTP/1.1


### datatable 테스트
GET http://localhost:8080/app/member/datatable.json HTTP/1.1

list: 66 {
    "draw": 17,
    "columns": [
        {
            "data": "id",
            "name": "id",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "username",
            "name": "username",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "name",
            "name": "name",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "1024",
                "regex": false
            }
        },
        {
            "data": "email",
            "name": "email",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        },
        {
            "data": "expiresOn",
            "name": "expiresOn",
            "searchable": true,
            "orderable": true,
            "search": {
                "value": "",
                "regex": false
            }
        }
    ],
    "order": [
        {
            "column": 0,
            "dir": "asc"
        }
    ],
    "start": 0,
    "length": 25,
    "search": {
        "value": "1024",
        "regex": false
    }
}